### ISSUE TITLE
Error detected

### ISSUE THREAD

**Issue by erichaus** [andbar-ru/vim-unicon#2]
Hello,

I just installed this by git cloning into my ~/.vim/bundle directory and then adding the following to `.vimrc`:

```
set t_Co=256
set background=light
colorscheme unicon
```

when I do `vim <file>` I get this first

![image](https://cloud.githubusercontent.com/assets/230757/18844543/7dfcf63c-83d2-11e6-88c8-d655a22b66e3.png)

**Comment by andbar-ru** [comment]
What operating system, terminal and how many colors does terminal support?
Output of command `echo $TERM`?
Output of command `tput colors`?
